#!/bin/bash

autopep8 --diff \
         --aggressive \
         --aggressive \
         --verbose \
         ./petri_net_interpreter/*.py

autopep8 --in-place \
         --aggressive \
         --aggressive \
         --verbose \
         ./petri_net_interpreter/*.py
